const LOCATIONS = [
    { name: "Aliana Clinic", url: "https://www.kelsey-seybold.com/find-a-location/aliana-clinic" },
    { name: "Atascocita Clinic", url: "https://www.kelsey-seybold.com/find-a-location/atascocita-clinic" },
    { name: "Bay Area Campus", url: "https://www.kelsey-seybold.com/find-a-location/bay-area-campus" },
    { name: "Baytown Clinic", url: "https://www.kelsey-seybold.com/find-a-location/baytown-clinic" },
    { name: "Berthelsen Main Campus", url: "https://www.kelsey-seybold.com/find-a-location/berthelsen-main-campus" },
    { name: "Conroe Clinic", url: "https://www.kelsey-seybold.com/find-a-location/conroe-clinic" },
    { name: "Downtown at Esperson Tunnel", url: "https://www.kelsey-seybold.com/find-a-location/downtown-at-esperson-tunnel" },
    { name: "Downtown Clinic", url: "https://www.kelsey-seybold.com/find-a-location/downtown-clinic" },
    { name: "Eldridge Clinic", url: "https://www.kelsey-seybold.com/find-a-location/eldridge-clinic" },
    { name: "Fairfield Clinic", url: "https://www.kelsey-seybold.com/find-a-location/fairfield-clinic" },
    { name: "Fort Bend Campus", url: "https://www.kelsey-seybold.com/find-a-location/fort-bend-campus" },
    { name: "Greater Heights Clinic", url: "https://www.kelsey-seybold.com/find-a-location/greater-heights-clinic" },
    { name: "Gulfgate Clinic", url: "https://www.kelsey-seybold.com/find-a-location/gulfgate-clinic" },
    { name: "Huntsville Clinic", url: "https://www.kelsey-seybold.com/find-a-location/huntsville-clinic" },
    { name: "Katy Clinic", url: "https://www.kelsey-seybold.com/find-a-location/katy-clinic" },
    { name: "Kingwood Clinic", url: "https://www.kelsey-seybold.com/find-a-location/kingwood-clinic" },
    { name: "Lake Houston Campus", url: "https://www.kelsey-seybold.com/find-a-location/lake-houston-campus" },
    { name: "Lake Jackson Clinic", url: "https://www.kelsey-seybold.com/find-a-location/lake-jackson" },
    { name: "Memorial City Clinic", url: "https://www.kelsey-seybold.com/find-a-location/memorial-city-clinic" },
    { name: "Memorial Villages Campus", url: "https://www.kelsey-seybold.com/find-a-location/memorial-villages-campus" },
    { name: "Meyerland Clinic", url: "https://www.kelsey-seybold.com/find-a-location/meyerland-clinic" },
    { name: "North Channel Clinic", url: "https://www.kelsey-seybold.com/find-a-location/north-channel-clinic" },
    { name: "North Houston Campus", url: "https://www.kelsey-seybold.com/find-a-location/north-houston-campus" },
    { name: "Northwest Campus (Cypress Clinic)", url: "https://www.kelsey-seybold.com/find-a-location/northwest-campus" },
    { name: "Pasadena Clinic", url: "https://www.kelsey-seybold.com/find-a-location/pasadena-clinic" },
    { name: "Pearland Clinic", url: "https://www.kelsey-seybold.com/find-a-location/pearland-clinic" },
    { name: "Rice Village OB/GYN", url: "https://www.kelsey-seybold.com/find-a-location/rice-village-obgyn" },
    { name: "River Oaks Clinic", url: "https://www.kelsey-seybold.com/find-a-location/river-oaks-clinic" },
    { name: "Rosenberg Clinic", url: "https://www.kelsey-seybold.com/find-a-location/rosenberg-clinic" },
    { name: "Sienna Clinic", url: "https://www.kelsey-seybold.com/find-a-location/sienna-clinic" },
    { name: "Sleep Center", url: "https://www.kelsey-seybold.com/find-a-location/sleep-center" },
    { name: "South Shore Harbour Clinic", url: "https://www.kelsey-seybold.com/find-a-location/south-shore-harbour-clinic" },
    { name: "Springwoods Village Campus", url: "https://www.kelsey-seybold.com/find-a-location/springwoods-village" },
    { name: "St. Luke's Medical Tower", url: "https://www.kelsey-seybold.com/find-a-location/st-lukes-medical-tower" },
    { name: "Stafford Clinic", url: "https://www.kelsey-seybold.com/find-a-location/stafford-clinic" },
    { name: "Summer Creek Clinic", url: "https://www.kelsey-seybold.com/find-a-location/summer-creek-clinic" },
    { name: "Tanglewood Clinic", url: "https://www.kelsey-seybold.com/find-a-location/tanglewood-clinic" },
    { name: "The Vintage Clinic", url: "https://www.kelsey-seybold.com/find-a-location/the-vintage-clinic" },
    { name: "The Woodlands Clinic", url: "https://www.kelsey-seybold.com/find-a-location/the-woodlands-clinic" },
    { name: "The Woodlands OB/GYN and Women's Health", url: "https://www.kelsey-seybold.com/find-a-location/the-woodlands-obgyn-and-womens-health" },
    { name: "Upper Kirby Clinic", url: "https://www.kelsey-seybold.com/find-a-location/upper-kirby-clinic" },
    { name: "West Campus", url: "https://www.kelsey-seybold.com/find-a-location/west-campus" },
    { name: "West University Clinic", url: "https://www.kelsey-seybold.com/find-a-location/west-university-clinic" },
    { name: "West Woodlands Clinic", url: "https://www.kelsey-seybold.com/find-a-location/west-woodlands-clinic" },
    { name: "Westchase Clinic", url: "https://www.kelsey-seybold.com/find-a-location/westchase-clinic" },
];
