const SPECIALTIES = [
    { name: "Adolescent Medicine", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/adolescent-medicine" },
    { name: "Allergy", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/allergy" },
    { name: "Anesthesiology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/anesthesiology" },
    { name: "Audiology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/audiology" },
    { name: "Bariatric Surgery", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/bariatric-surgery" },
    { name: "Behavioral Medicine", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/behavioral-medicine" },
    { name: "Breast Diagnostic Center", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/breast-diagnostic-center" },
    { name: "Cardiology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/cardiology" },
    { name: "Chiropractic Care", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/chiropractic-care" },
    { name: "Cosmetic Dermatology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/cosmetic-dermatology" },
    { name: "Critical Care", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/critical-care" },
    { name: "Dermatology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/dermatology" },
    { name: "Dermatopathology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/dermatopathology" },
    { name: "Dietitian and Nutrition Services", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/dietitian-and-nutrition-services" },
    { name: "Electrodiagnostic Medicine", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/electrodiagnostic-medicine" },
    { name: "Endocrinology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/endocrinology" },
    { name: "ENT", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/ent" },
    { name: "Executive Health", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/executive-health" },
    { name: "Family Medicine", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/family-medicine" },
    { name: "Gastroenterology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/gastroenterology" },
    { name: "Gynecology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/gynecology" },
    { name: "Hand Surgery", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/hand-surgery" },
    { name: "Hematology/Oncology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/hematologyoncology" },
    { name: "Home Care Medicine", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/home-care-medicine" },
    { name: "Hospitalist", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/hospitalist" },
    { name: "Infectious Disease", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/infectious-disease" },
    { name: "Internal Medicine", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/internal-medicine" },
    { name: "Interventional Cardiology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/interventional-cardiology" },
    { name: "Interventional Pain Management", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/interventional-pain-management" },
    { name: "Mohs Surgery", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/mohs-surgery" },
    { name: "Nephrology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/nephrology" },
    { name: "Neurology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/neurology" },
    { name: "Neurosurgery", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/neurosurgery" },
    { name: "OB/GYN", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/obgyn" },
    { name: "Ophthalmology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/ophthalmology" },
    { name: "Optometry", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/optometry" },
    { name: "Orthopedic Surgery", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/orthopedic-surgery" },
    { name: "Orthopedics", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/orthopedics" },
    { name: "Otolaryngology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/otolaryngology" },
    { name: "Palliative Care", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/palliative-care" },
    { name: "Pediatrics", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/pediatrics" },
    { name: "Physical Medicine and Rehabilitation", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/physical-medicine-and-rehabilitation" },
    { name: "Plastic Surgery", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/plastic-surgery" },
    { name: "Podiatry", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/podiatry" },
    { name: "Primary Care", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/primary-care" },
    { name: "Pulmonary Medicine", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/pulmonary-medicine" },
    { name: "Radiation Oncology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/radiation-oncology" },
    { name: "Radiology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/radiology" },
    { name: "Rheumatology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/rheumatology" },
    { name: "Sleep Medicine", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/sleep-medicine" },
    { name: "Spine", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/spine" },
    { name: "Spine Center", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/spine-center" },
    { name: "Sports Medicine", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/sports-medicine" },
    { name: "Surgery", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/surgery" },
    { name: "Urology", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/urology" },
    { name: "Wound Care", url: "https://www.kelsey-seybold.com/find-a-houston-doctor/specialty/wound-care" },
];
