const SPECIALTIES = [
    { name: "Allergy", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/allergy-and-immunology" },
    { name: "Ambulatory Surgery Centers", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/surgery/surgery-center" },
    { name: "Breast Diagnostic Center", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/cancer-center/breast-diagnostic-center" },
    { name: "Cancer Center", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/cancer-center" },
    { name: "Cardiology - Cardiovascular Disease", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/cardiology" },
    { name: "Chiropractic Care", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/chiropractic-care" },
    { name: "Cosmetic Services", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/cosmetic-services" },
    { name: "Dermatology - Adult", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/dermatology" },
    { name: "Dermatology - Cosmetic", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/dermatology/services/cosmetic" },
    { name: "Dermatology - Pediatrics", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/dermatology/services/pediatric" },
    { name: "Diabetes Care", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/endocrinology/diabetes" },
    { name: "Ear, Nose and Throat (ENT)", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/ent" },
    { name: "Endocrinology", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/endocrinology" },
    { name: "Eye Care (Optometry, Ophthalmology)", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/eye-doctors" },
    { name: "Family Medicine", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/family-medicine" },
    { name: "Gastroenterology", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/gastroenterology" },
    { name: "Gynecology", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/obgyn/womens-health" },
    { name: "Hospitalists - Adult", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/hospitalist" },
    { name: "Infectious Disease", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/infectious-disease" },
    { name: "Internal Medicine", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/internal-medicine" },
    { name: "Minimally Invasive Surgery", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/obgyn/minimally-invasive-surgery" },
    { name: "Mohs Surgery", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/surgery/mohs-surgery" },
    { name: "Neurology", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/neurology" },
    { name: "Nuclear Medicine", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/nuclear-medicine" },
    { name: "Obstetrics", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/obgyn/obstetrics" },
    { name: "Obstetrics and Gynecology (OB/GYN)", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/obgyn" },
    { name: "Ophthalmology", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/ophthalmology" },
    { name: "Orthopedics", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/orthopedics" },
    { name: "Orthopedics - Sports Medicine", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/sports-medicine" },
    { name: "Palliative Care", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/palliative-care" },
    { name: "Pediatrics", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/pediatrics" },
    { name: "Physical Medicine and Rehabilitation", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/physical-medicine-and-rehabilitation" },
    { name: "Plastic Surgery and Aesthetics", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/plastic-surgery" },
    { name: "Podiatry", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/podiatry" },
    { name: "Primary Care", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/primary-care" },
    { name: "Pulmonary Medicine - Adult", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/pulmonary" },
    { name: "Radiation Oncology", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/cancer-center/radiation-therapy-radiosurgery" },
    { name: "Radiology - Adult", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/radiology" },
    { name: "Rheumatology", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/rheumatology" },
    { name: "Sleep Medicine", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/pulmonary/sleep-center" },
    { name: "Spine Center", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/spine" },
    { name: "Surgery - Robotic", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/surgery/surgery-center/robotic-surgery" },
    { name: "Travel Medicine", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/travel-clinic" },
    { name: "Urology", url: "https://www.kelsey-seybold.com/medical-services-and-specialties/urology" },
];
